### ISSUE TITLE
tt

### ISSUE THREAD

**Issue by GHppxia** [zodf0055980/k-means-AFL#1]

**Comment by zodf0055980** [comment]
能給我看 group_seed.py 執行時所顯示的分群結果嗎?
經過我的實驗，這種分群並進行選擇的方法對於大型程式的模糊測試是有效果的。
![2021-07-14_092848](https://user-images.githubusercontent.com/25863161/125546220-9cb89298-63cf-4ab1-aa35-7fd154ffb3d8.png)

AFL-kmeans 是此專案，[Yuan-fuzz](https://github.com/zodf0055980/Yuan-fuzz) 是我另一個實作的專案

**Comment by xia15** [comment]
fit_bitmap:



cluster_labels:



后面输出的这些提示信息



我不知道是不是项目哪里没有运行正确，显示的结果不理想，期待你的回复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zodf0055980/k-means-AFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 上午9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zodf0055980/k-means-AFL] tt (#1)





 
能給我看 group_seed.py 執行時所顯示的分群結果嗎?
 經過我的實驗，這種分群並進行選擇的方法對於大型程式的模糊測試是有效果的。

**Comment by zodf0055980** [comment]
沒看到結果歐 你再傳一次試試

**Comment by xia15** [comment]
fit_bitmap:
 

 
cluster_labels:
 

 
后面输出的这些提示信息
 

 
&nbsp;

     
                




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zodf0055980/k-means-AFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上6:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zodf0055980/k-means-AFL] tt (#1)





 
沒看到結果歐 你再傳一次試試

**Comment by xia15** [comment]
你好，请问可以看到结果吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zodf0055980/k-means-AFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上6:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zodf0055980/k-means-AFL] tt (#1)





 
沒看到結果歐 你再傳一次試試

**Comment by zodf0055980** [comment]
不行歐 看不到

**Comment by xia15** [comment]
fit_bitmap:



cluster_labels:

后面输出提示信息：







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zodf0055980/k-means-AFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 下午3:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zodf0055980/k-means-AFL] tt (#1)





 
不行歐 看不到

**Comment by zodf0055980** [comment]
還是無法 你要不要試試貼文字或是檔案阿

**Comment by xia15** [comment]
我前面有一次就是发的文档，但是你说没有看到








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zodf0055980/k-means-AFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 晚上6:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zodf0055980/k-means-AFL] tt (#1)





 
還是無法 你要不要試試貼文字或是檔案阿

**Comment by zodf0055980** [comment]
你看一下 https://github.com/zodf0055980/k-means-AFL/issues/1 真的沒有@@

**Comment by xia15** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zodf0055980/k-means-AFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上6:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zodf0055980/k-means-AFL] tt (#1)





 
沒看到結果歐 你再傳一次試試

**Comment by xia15** [comment]
你没有收到我昨天法的文件吗？

**Comment by zodf0055980** [comment]
沒有 你要不要用網站上傳試試？

**Comment by xia15** [comment]
***@***.***邮箱，你查收一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zodf0055980/k-means-AFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月16日(星期五) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zodf0055980/k-means-AFL] tt (#1)





 
沒有 你要不要用網站上傳試試？

**Comment by zodf0055980** [comment]
我一直沒有收到你的信，我在此做最後的回覆。
執行的結果大概會長這個樣子。
```
[*] port = 6668
[*] dirpath = ./xmlout
[*] init_seed_count = 1
[*] kmeans_group = 20
['/home/yuan/libxml2/xmllint', './xmlout/queue/id:000000,orig:small_document.xml']
.....
['/home/yuan/libxml2/xmllint', './xmlout/queue/id:000412,src:000000,op:havoc,rep:2']
[*] cluster_labels
[ 5 10 12  9  6  8  6  9 12 12  9  3 12  8  1  9  4 12 19  6  8 15  8  1
  1  9  6  9  1 15 17  8  4 15  6  6  1 19  6 17 17 12  3 19 12 19  9  4
  9  9 19  6  9  9 13  9 12 17  1 12  6  6  9 15  8  8  6  8  6  4  1  6
 17 19 19  6  8  9  1 17 12  3  1  8  8  3 17  6 13  4  6 17 19  4 15  8
  1  4 19 15  6  6 19  8  8 12 13  1  1  8 19  3 13  3  6 13 15  4 19  1
 15 19 13  3  3  1  3 19 15 19  8 19 19  3  3 15 13  4  1 13 19  3 12 19
  3  3  6  3  4  3 10 10 14 10 14 11 11 11 11  2 11 11  2  2  2  2  2  2
 18 18 18 18 18 14  7  7  7  0  7  0  7 14 14 14 10 10 11 16 11 16 11  2
  2  7  0  0 10  5 11 11  2 18  7  0  0  7 14 11 11  7 11 18  0 10 10 10
  5 11 18  2 18  5  7  7  0  0  0  0  0 14 10 10 16  5 14 14 10 11 10 11
 16 18 18  7  7  7  7  7  0 14 14 10 10 18  7  7 10 10 16 18  2 11 10 10
 10  2  2 10 14 18  7  2 10 11  7  0 10 14 10 14  2 10  5 16 10 18  0 18
  5 16 11 18 10  0 10 11 11 11 10 14 11 10 11  5 16 11  2 14  7 16 18  5
 16 10  5  2  0 11 18  2  2 14  7  0 10  0 10 14 10 11 11  7 10  0  2  2
  5 16 11  0  2 14 10 11  7 11  0 18 18 18 18 14  7 10  7  0  2 11  7  0
 11  5 10 14 14 14  0 11  7 11 10 10 10  7  0 10 10  2  5 18 10  5 10  0
 10  7 11  2  2  7  0 18 18 16 18  7 16  2  2 18  0  0 16 10  0  5 14 11
 14  7  0 16  5]
[*] show group
group 0 : 177, 179, 194, 195, 203, 204, 212, 224, 225, 226, 227, 228, 248, 275, 286, 293, 316, 323, 325, 333, 339, 346, 355, 359, 366, 374, 383, 390, 400, 401, 404, 410
group 1 : 14, 23, 24, 28, 36, 58, 70, 78, 82, 96, 107, 108, 119, 125, 138
group 2 : 159, 162, 163, 164, 165, 166, 167, 191, 192, 200, 219, 260, 265, 266, 271, 280, 306, 315, 319, 320, 334, 335, 340, 356, 377, 387, 388, 397, 398
group 3 : 11, 42, 81, 85, 111, 113, 123, 124, 126, 133, 134, 141, 144, 145, 147, 149
group 4 : 16, 32, 47, 69, 89, 93, 97, 117, 137, 148
group 5 : 197, 216, 221, 233, 282, 288, 303, 311, 314, 336, 361, 378, 381, 405, 412, 0
group 6 : 4, 6, 19, 26, 34, 35, 38, 51, 60, 61, 66, 68, 71, 75, 87, 90, 100, 101, 114, 146
group 7 : 174, 175, 176, 178, 180, 193, 202, 205, 209, 222, 223, 243, 244, 245, 246, 247, 254, 255, 270, 274, 308, 322, 331, 344, 352, 354, 358, 368, 373, 385, 389, 395, 409
group 8 : 5, 13, 20, 22, 31, 64, 65, 67, 76, 83, 84, 95, 103, 104, 109, 130
group 9 : 3, 7, 10, 15, 25, 27, 46, 48, 49, 52, 53, 55, 62, 77
group 10 : 1, 150, 151, 153, 184, 185, 196, 213, 214, 215, 230, 231, 236, 238, 251, 252, 256, 257, 262, 263, 264, 267, 272, 276, 278, 281, 284, 292, 294, 298, 301, 313, 324, 326, 328, 332, 342, 353, 362, 370, 371, 372, 375, 376, 380, 382, 384, 403
group 11 : 155, 156, 157, 158, 160, 161, 186, 188, 190, 198, 199, 207, 208, 210, 217, 237, 239, 261, 273, 290, 295, 296, 297, 300, 302, 305, 317, 329, 330, 338, 343, 345, 357, 360, 367, 369, 386, 407
group 12 : 2, 8, 9, 12, 17, 41, 44, 56, 59, 80, 105, 142
group 13 : 54, 88, 106, 112, 115, 122, 136, 139
group 14 : 152, 154, 173, 181, 182, 183, 206, 229, 234, 235, 249, 250, 268, 277, 279, 299, 307, 321, 327, 341, 351, 363, 364, 365, 406, 408
group 15 : 21, 29, 33, 63, 94, 99, 116, 120, 128, 135
group 16 : 187, 189, 232, 240, 258, 283, 289, 304, 309, 312, 337, 393, 396, 402, 411
group 17 : 30, 39, 40, 57, 72, 79, 86, 91
group 18 : 168, 169, 170, 171, 172, 201, 211, 218, 220, 241, 242, 253, 259, 269, 285, 287, 291, 310, 318, 347, 348, 349, 350, 379, 391, 392, 394, 399
group 19 : 18, 37, 43, 45, 50, 73, 74, 92, 98, 102, 110, 118, 121, 127, 129, 131, 132, 140, 143
[*] run rarget = 177
```
如果有成功分群，就代表有成功執行。

**Comment by xia15** [comment]
你能给我讲一下你这个使用k-means进行种子选择的具体想法，原理吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zodf0055980/k-means-AFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月29日(星期四) 下午4:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zodf0055980/k-means-AFL] tt (#1)





 
Closed #1.
